# swagger 常量
swagger:
  basePackage: com.qezhhnjy.login
  title: Sara项目使用Swagger2构建RestFul API
  description: 更多Spring Boot相关文章请关注：http://blog.didispace.com/
  service: http://blog.didispace.com/
  name: qezhhnjy
  url: www.fzyszsz.com
  email: fzyszsz@163.com
  version: 1.0
spring:

  # devtools 配置
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #按字段名字建表
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  messages:
    basename: myconfig
server:
  servlet:
    context-path: /
  port: 8888



