spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sara?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false


server:
  tomcat:
    uri-encoding: utf-8

