spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sara?useSSL=false
    username: root
    password: 123
  profiles:
    active: dev


server:
  tomcat:
    uri-encoding: utf-8
  port: 8888

